language: python
os: linux
cache:
    pip: true
matrix:
    include:
        - python: "3.8"
          env: NOXSESSION="tests-3.8"
        - python: "3.8"
          env: NOXSESSION="lint"
        - python: "3.8"
          env: NOXSESSION="build"
install:
    - pip install nox

script:
    - nox --non-interactive --session "$NOXSESSION"
